// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALwMLjdRfiQhwoRdJSYvv5QB20SUQGd34',
    appId: '1:901269435905:web:e57c8dd945313b6e87b200',
    messagingSenderId: '901269435905',
    projectId: 'myapp-df5db',
    authDomain: 'myapp-df5db.firebaseapp.com',
    storageBucket: 'myapp-df5db.appspot.com',
    measurementId: 'G-YM8GK795Z2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMeuEH5S7I67xNZl6xzWt2KRrSRHtFMbY',
    appId: '1:901269435905:android:4001d7d3f184644487b200',
    messagingSenderId: '901269435905',
    projectId: 'myapp-df5db',
    storageBucket: 'myapp-df5db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV3aA8ajFaaeWuOrv3-_7XdBW33AeGMus',
    appId: '1:901269435905:ios:16d3676a06ab581a87b200',
    messagingSenderId: '901269435905',
    projectId: 'myapp-df5db',
    storageBucket: 'myapp-df5db.appspot.com',
    iosClientId:
        '901269435905-2f6hjr1otg981pvbjr0inqgeshf9o0fr.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV3aA8ajFaaeWuOrv3-_7XdBW33AeGMus',
    appId: '1:901269435905:ios:9985995930b19d4c87b200',
    messagingSenderId: '901269435905',
    projectId: 'myapp-df5db',
    storageBucket: 'myapp-df5db.appspot.com',
    iosClientId:
        '901269435905-cfsmfoj94nqotao3ihj37bfvrevealca.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
